### ISSUE TITLE
Obsolete usage of importing web components in demo files

### ISSUE THREAD

**Issue by groowyCZ** [kantoniak/piano-keyboard#1]
Hello,
I really like this project and I would love to use it in my school project but the way of importing the `piano-keyboard` element in your demo files is already obsolete. Could you please update them to work?

Thank you

**Comment by kantoniak** [comment]
I'm glad you liked it ☺ I haven't done any webdev for a while, but I'll take a look at this in the evening.

**Comment by kantoniak** [comment]
I've updated the code to run on ES6 modules, which works with modern browsers. Code breaks with `SCRIPT5022: SCRIPT5022: Syntax error` in Edge, but I ran validators and stuff and I cannot find the problem.
I'm closing this issue for now, but feel free to investigate it ;)
